# Dependencies
markdown:             kramdown
highlighter:          rouge

# Permalinks
permalink:            pretty

# Setup
title:                Mark Holloway
tagline:              Mark Holloway Personal Site
description:          My personal blog - on Python development, 3D graphics, compositing, and film. 
url:                  https://markholloway.github.io
baseurl:
paginate:             5
name:                 Mark Holloway

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist

# SEO
twitter:
  username:           <username>
  url:                https://twitter.com/<username>
social:
  name:               Mark Holloway
  links:
    - http://linkedin.com/in/mholloway
    - https://github.com/markholloway

# Custom vars
custom_pages:
  feed:               /atom.xml
github:
    url:              https://github.com/markholloway
    repo:             https://github.com/markholloway/markholloway.github.io
excerpt_separator:    <!--more-->
google_analytics:     UA-131536379-1
hyde_version:         2.1.0
hyde_url:             http://hyde.getpoole.com
hyde_repo:            https://github.com/poole/hyde
show_related_posts:   false
force_https:          true

  
# Comments 
comments:
  use_disqus:         false
  use_googleplus:     false
  disqus_shortname:   mh-blog-2
